# run: conda env create --file environment.yml
name: photoMontage
dependencies:
    - python=3.7.3
    - opencv
    - tk=8.6.8
    - setuptools=41.2.0
    - cython=0.29.13
    - numpy
    - pip=19.2.3
    - pip:
        - PyMaxflow==1.2.12
    - pillow=6.2.0
    - matplotlib
